name: abantether
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  retrofit_generator: ^9.1.5
  freezed: ^2.5.7
  build_runner: ^2.4.13
  go_router: ^14.8.0
  injectable: ^2.5.0
  flutter_secure_storage: ^9.2.4
  injectable_generator: ^2.6.2
  freezed_annotation: ^2.4.4
#  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
  assets:
     - assets/lottie/login.json
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

